### ISSUE TITLE
How is hyperparameter search done in the codebase? 

### ISSUE THREAD

**Issue by LeenaShekhar** [allenai/vampire#41]
I understand this is more of an AllenNLP framework question than VAMPIRE related, but since I am using this model I would just ask this here for quick response.

How exactly is hyper-parameter search done? I see a folder search-spaces with various json files and one jsonnet file with key:value like:

    **"VAE_HIDDEN_DIM": {
        "sampling strategy": "integer",
        "bounds": [64, 128]   
    },**

But I could not figure out how exactly to pass this config file to the model. I replaced the VAMPIRE dict in environment.py ("VAE_HIDDEN_DIM": 128,) with the one in vampire_ag_search.json (shown above in bold) but that threw error. 

One workaround would be to have many config files with different values (let's say dimensions 64, 80, 100, 128) and train all models separately, but my guess is that is not the right way here.

**Comment by kernelmachine** [comment]
@LeenaShekhar here's the repo: github.com/allenai/allentune. I'll leave this open till I run an additional test of the search space configurations in this repo.
