### ISSUE TITLE
RuntimeError: bincount only supports 1-d non-negative integral inputs.

### ISSUE THREAD

**Issue by RamanRajarathinam** [allenai/vampire#45]
When I tried to execute

> python -m scripts.train --config training_config/classifier.jsonnet --serialization-dir model_logs/clf --environment CLASSIFIER --device 0

the following error happens,

>  File "/home/raman/nlp/lib/python3.6/site-packages/allennlp/modules/token_embedders/bag_of_word_counts_token_embedder.py", line 75, in forward
    vec = torch.bincount(document, minlength=self.vocab_size).float()
RuntimeError: bincount only supports 1-d non-negative integral inputs.
2019-09-19 14:10:50,622 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpzvnq_hx6

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/raman/vampire/scripts/train.py", line 75, in <module>
    main()
  File "/home/raman/vampire/scripts/train.py", line 71, in main
    subprocess.run(" ".join(allennlp_command), shell=True, check=True)
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'allennlp train --include-package vampire training_config/classifier.jsonnet -s model_logs/clf' returned non-zero exit status 1.

I am using allennlp 0.8.4 version. Can someone please help me on this?

**Comment by kernelmachine** [comment]
What's your vocabulary size? Are you running this on custom data, or the tutorial in the README?

**Comment by RamanRajarathinam** [comment]
Tutorial in README, whatever you have mentioned there exactly like that!

**Comment by kernelmachine** [comment]
I'm unfortunately unable to reproduce the error, even with allennlp 0.8.4. Can you try running via the docker container and see if it works there?
