### ISSUE TITLE
Collab Notebook Not Working

### ISSUE THREAD

**Issue by AbhirajHinge** [allenai/vampire#46]
I am trying to get Vampire to run on a Google Collab notebook. I have copied over the example from this repository to a [Google Collab notebook](https://colab.research.google.com/drive/1s4RMAnfhiKFG6KjtxCI3YGHTcoEu4V34#scrollTo=_UwVjCvq2azP).
However, running the notebook as is, does not work.
Is there anything wrong with what I've done?

**Comment by kernelmachine** [comment]
I'm unable to see that google colab notebook. Can you be more specific as to the issues you are seeing? A stack trace would be useful!

**Comment by AbhirajHinge** [comment]
Hey,
So, I get this error when I try to run the example provided on the collab.

`Traceback (most recent call last):
 File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
 File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
 File "/content/vampire/scripts/preprocess_data.py", line 10, in <module>
    from allennlp.data.tokenizers.word_splitter import SpacyWordSplitter
ModuleNotFoundError: No module named 'allennlp.data.tokenizers.word_splitter'`

The command I am attempting to run is - 
`!python -m scripts.preprocess_data \
            --train-path examples/ag/train.jsonl \
            --dev-path examples/ag/dev.jsonl \
            --tokenize \
            --tokenizer-type spacy \
            --vocab-size 30000 \
            --serialization-dir examples/ag`

You can find the Collab notebook [here](https://colab.research.google.com/drive/1s4RMAnfhiKFG6KjtxCI3YGHTcoEu4V34), if it is still needed.

**Comment by kernelmachine** [comment]
Hey there, sorry about the delay. see #49
