### ISSUE TITLE
E   ImportError: cannot import name 'WordTokenizer' from 'allennlp.data.tokenizers' 

### ISSUE THREAD

**Issue by bjayakumar** [allenai/vampire#48]
`
===================================================================================================== ERRORS ======================================================================================================
_______________________________________________________ ERROR collecting vampire/tests/data/dataset_readers/semisupervised_text_classification_json_test.py _______________________________________________________
ImportError while importing test module '/Others_Models/vampire/vampire/tests/data/dataset_readers/semisupervised_text_classification_json_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
vampire/tests/data/dataset_readers/semisupervised_text_classification_json_test.py:8: in <module>
    from vampire.data.dataset_readers import SemiSupervisedTextClassificationJsonReader
vampire/data/__init__.py:1: in <module>
    from vampire.data.dataset_readers import SemiSupervisedTextClassificationJsonReader
vampire/data/dataset_readers/__init__.py:1: in <module>
    from vampire.data.dataset_readers.semisupervised_text_classification_json import (
vampire/data/dataset_readers/semisupervised_text_classification_json.py:12: in <module>
    from allennlp.data.tokenizers import Tokenizer, WordTokenizer
E   ImportError: cannot import name 'WordTokenizer' from 'allennlp.data.tokenizers' (~/.conda/envs/allennlp/lib/python3.7/site-packages/allennlp/data/tokenizers/__init__.py)
______________________________________________________________________________ ERROR collecting vampire/tests/models/vampire_test.py ______________________________________________________________________________
ImportError while importing test module '/Others_Models/vampire/vampire/tests/models/vampire_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
vampire/tests/models/vampire_test.py:8: in <module>
    from vampire.data.dataset_readers import VampireReader
vampire/data/__init__.py:1: in <module>
    from vampire.data.dataset_readers import SemiSupervisedTextClassificationJsonReader
vampire/data/dataset_readers/__init__.py:1: in <module>
    from vampire.data.dataset_readers.semisupervised_text_classification_json import (
vampire/data/dataset_readers/semisupervised_text_classification_json.py:12: in <module>
    from allennlp.data.tokenizers import Tokenizer, WordTokenizer
E   ImportError: cannot import name 'WordTokenizer' from 'allennlp.data.tokenizers' (/.conda/envs/allennlp/lib/python3.7/site-packages/allennlp/data/tokenizers/__init__.py)
`

I did not have any issues with installation.

**Comment by kernelmachine** [comment]
Hey there, sorry about the delay. see #49

**Comment by rouliandu** [comment]
this error still happen, what should i do

**Comment by wangjinjie722** [comment]
> this error still happen, what should i do

yes it still happends, what should we do

**Comment by wangjinjie722** [comment]
> this error still happen, what should i do

hi, you can use 0.9.0 allennlp, it works for me
